#server
server:
  port: 80
  servlet:
    context-path: /
  tomcat:
    max-threads: 1000
#spring
spring:
  datasource:
    url: jdbc:mysql:///wmcx?serverTimezone=GMT%2B8&characterEncoding=utf8
    username: root
    password: 123
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    
#  aop:
#     proxy-target-class: false
#mybatis
mybatis:
  configuration:
    default-statement-timeout: 30
    map-underscore-to-camel-case: true
  mapper-locations:
  - classpath:/mapper/*/*.xml
#LOG
logging:
  level:
    com.ws: DEBUG
